# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development: &development
  <<: *default
  host: localhost
  username: root
  password:
  database: <%= Rails.application.engine_name.gsub(/_application/,'').downcase %>_development

test: &test
  <<: *default
  host: localhost
  username: root
  password:
  database: <%= Rails.application.engine_name.gsub(/_application/,'').downcase %>_test

production: &production
  <<: *default
  host: localhost
  database: <%= Rails.application.engine_name.gsub(/_application/,'').downcase %>_production
  username: your_production_database_login
  password: your_production_database_password
